server:
  port: ${IOT_SERVER_PORT}
  servlet:
    context-path: ${IOT_CONTEXT_PATH}

authorization:
  app-secret: ${IOT_APP_SECRET}
  yandex-home-token: ${YANDEX_HOME_TOKEN}

home:
  max-temperature: ${HOME_MAX_TEMPERATURE}
  min-temperature: ${HOME_MIN_TEMPERATURE}
  auto-ac: ${HOME_AUTO_AC}
  temperature-check-cron: ${TEMPERATURE_CHECK_CRON}